### ISSUE TITLE
Filter url on ALP

### ISSUE THREAD

**Issue by maxserv-woostelbos** [EmicoEcommerce/Magento2AttributeLanding#15]
Hi, 

We have a problem with the filters on attribute landingspages. I was wondering if you could help me find the best way to fix this. This is the case:

When you open a landingpage with a filter (check link below) there is a filter for 'materiaal' a default filter. So for so good.  

https://staging.magento.forza-intenso.keessmit.nl/materiaalsoorten/houten-tuinmeubelen/

But when you try to add another filter, for example a 'brand' the result will always be 0. The link thats generated is (so the materiaal->hout is added for a second time):

https://staging.magento.forza-intenso.keessmit.nl/materiaalsoorten/houten-tuinmeubelen/materiaal/hout/merk/forza-furniture/

What does seem to work is (so 'materiaal/hout/' is removed):

https://staging.magento.forza-intenso.keessmit.nl/materiaalsoorten/houten-tuinmeubelen/merk/forza-furniture/

When you try to add another 'materiaal' this trick does not seem to work at all:

https://staging.magento.forza-intenso.keessmit.nl/materiaalsoorten/houten-tuinmeubelen/materiaal/aluminium/

Maybe a good thing to know is that all of these examples have an ALP page with only the 'master category' selected. When an ALP has a subcategory assigned the problems do not seem to occour.

**Comment by edwinljacobs** [comment]
Hi,

I am unable to check this today, however I will look into these examples next week (wednesday at the latest). There have been some releases (most notably on https://github.com/EmicoEcommerce/Magento2AttributeLandingTweakwise and https://github.com/EmicoEcommerce/Magento2Tweakwise) perhaps something went wrong. 

I cannot open these links as they require basic auth. If you want I can share my email address so that you can send me the credentials. I could also try to reproduce these issues on my own installation. The extra filter "materiaal/hout" when selecting a brand https://staging.magento.forza-intenso.keessmit.nl/materiaalsoorten/houten-tuinmeubelen/materiaal/hout/merk/forza-furniture/ seems weird. 

What exactly do you mean by: "But when you try to add another filter, for example a 'brand' the result will always be 0"? No results?

Perhaps there is a conflicting rewrite in the rewrite table, you could check if there is something up there.

**Comment by edwinljacobs** [comment]
closed due to inactivity
